name: Create Release with Zip File

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Create Zip File
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      
      - name: Install dependencies
        run: npm install
        working-directory: web

      - name: Build web
        run: npm run build
        working-directory: web

      - name: Prepare final package folder
        run: |
          mkdir -p ./temp/st_company_app
          # Copy the necessary files while preserving directory structure
          cp --parents client/* server/* ./temp/st_company_app/
          cp config.lua fxmanifest.lua ./temp/st_company_app/

          # If web/build exists, include it
          if [ -d "./web/build" ]; then
            mkdir -p ./temp/st_company_app/web
            cp -r ./web/build ./temp/st_company_app/web/build
          fi

          # Create the zip file of the release package
          cd ./temp && zip -r ../st_company_app.zip ./st_company_app

      - name: Upload st_company_app.zip to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./st_company_app.zip
          asset_name: st_company_app.zip
          asset_content_type: application/zip