name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  create-release:
    name: Build and Create Tagged Release
    runs-on: ubuntu-latest

    steps:
      - name: Install Archive Tools
        run: sudo apt install zip

      - name: Checkout Source Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: "pnpm"
          cache-dependency-path: "web/pnpm-lock.yaml"

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile
        working-directory: web

      - name: Run Build
        run: pnpm build
        working-directory: web
        env:
          CI: false

      - name: Bump Manifest Version
        run: node .github/actions/bump-manifest-version.js
        env:
          TGT_RELEASE_VERSION: v${{ github.ref_name }}

      - name: Push Manifest Change
        uses: EndBug/add-and-commit@v8
        with:
          add: fxmanifest.lua
          push: true
          author_name: Manifest Bumper
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "chore: bump manifest version to v${{ env.RELEASE_VERSION }}"

      - name: Update Tag Ref
        uses: EndBug/latest-tag@latest
        with:
          tag-name: v${{ env.RELEASE_VERSION }}

      - name: Bundle Files
        run: |
          mkdir -p ./temp/st_billing
          # Copy the necessary files while preserving directory structure
          cp --parents client/* server/* locales/* ./temp/st_billing/
          cp config.lua fxmanifest.lua ./temp/st_billing/

          # Copy README if it exists (case-insensitive)
          if [ -f "./README.md" ]; then
            cp ./README.md ./temp/st_billing/README.md
          elif [ -f "./readme.md" ]; then
            cp ./readme.md ./temp/st_billing/README.md
          elif [ -f "./readme" ]; then
            cp ./readme ./temp/st_billing/README.md
          fi

          # If web/build exists, include it
          if [ -d "./web/build" ]; then
            mkdir -p ./temp/st_billing/web
            cp -r ./web/build ./temp/st_billing/web/build
          fi

          # Create the zip file of the release package
          cd ./temp && zip -r ../st_billing.zip ./st_billing

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        id: auto_release
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "Release v${{ env.RELEASE_VERSION }}"
          prerelease: false
          files: st_billing.zip

        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}